#!/usr/bin/env python3
"""
Test script for insight generation functionality
"""
import asyncio
import sys
import os
from pathlib import Path

# Add the project root to Python path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from open_notebook.database.repository import db_connection
from open_notebook.domain.notebook import Source, SourceInsight
from open_notebook.domain.transformation import Transformation
from open_notebook.services.qdrant_service import qdrant_service
from loguru import logger


async def test_insight_generation():
    """Test insight generation end-to-end"""
    
    print("🧪 Testing Insight Generation")
    print("=" * 50)
    
    try:
        # 1. Test database connection
        print("1. Testing database connection...")
        async with db_connection() as conn:
            result = await conn.query("SELECT * FROM source LIMIT 1")
            print(f"   ✅ Database connected. Found {len(result)} sources")
        
        # 2. Test Qdrant connection
        print("\n2. Testing Qdrant connection...")
        try:
            await qdrant_service._ensure_client()
            await qdrant_service._ensure_collections()
            print("   ✅ Qdrant connected and collections ready")
        except Exception as e:
            print(f"   ⚠️  Qdrant connection failed: {e}")
            print("   This is expected if Qdrant is not running")
        
        # 3. Get a test source
        print("\n3. Finding test source...")
        sources = await Source.list()
        if not sources:
            print("   ❌ No sources found. Please create a source first.")
            return False
        
        test_source = sources[0]
        print(f"   ✅ Using source: {test_source.id} - {test_source.title}")
        
        # 4. Get a test transformation
        print("\n4. Finding test transformation...")
        transformations = await Transformation.list()
        if not transformations:
            print("   ❌ No transformations found. Please create a transformation first.")
            return False
        
        test_transformation = transformations[0]
        print(f"   ✅ Using transformation: {test_transformation.id} - {test_transformation.name}")
        
        # 5. Test insight creation
        print("\n5. Testing insight creation...")
        try:
            # Count existing insights
            existing_insights = await test_source.get_insights()
            initial_count = len(existing_insights)
            print(f"   Initial insight count: {initial_count}")
            
            # Create insight using add_insight method
            test_content = "This is a test insight generated by the test script."
            await test_source.add_insight(
                insight_type=test_transformation.name,
                content=test_content
            )
            
            # Check if insight was created
            updated_insights = await test_source.get_insights()
            final_count = len(updated_insights)
            print(f"   Final insight count: {final_count}")
            
            if final_count > initial_count:
                print("   ✅ Insight created successfully in SurrealDB")
                
                # Check the latest insight
                latest_insight = updated_insights[-1]
                print(f"   Insight ID: {latest_insight.id}")
                print(f"   Insight Type: {latest_insight.insight_type}")
                print(f"   Content Preview: {latest_insight.content[:100]}...")
                
                # 6. Test Qdrant storage
                print("\n6. Testing Qdrant storage...")
                try:
                    # Check if insight was stored in Qdrant
                    client = await qdrant_service._ensure_client()
                    scroll_result = client.scroll(
                        collection_name="source_insights",
                        scroll_filter={
                            "must": [
                                {
                                    "key": "source_id",
                                    "match": {"value": test_source.id}
                                }
                            ]
                        },
                        limit=10
                    )
                    
                    if scroll_result and scroll_result[0]:
                        print(f"   ✅ Found {len(scroll_result[0])} insights in Qdrant")
                        for point in scroll_result[0]:
                            print(f"   - Insight Type: {point.payload.get('insight_type')}")
                            print(f"   - Content Preview: {point.payload.get('content', '')[:50]}...")
                    else:
                        print("   ⚠️  No insights found in Qdrant (may be expected if embedding failed)")
                        
                except Exception as e:
                    print(f"   ⚠️  Qdrant check failed: {e}")
                
                return True
            else:
                print("   ❌ No new insight was created")
                return False
                
        except Exception as e:
            print(f"   ❌ Insight creation failed: {e}")
            logger.exception(e)
            return False
            
    except Exception as e:
        print(f"❌ Test failed with error: {e}")
        logger.exception(e)
        return False


async def test_transformation_graph():
    """Test the transformation graph directly"""
    
    print("\n🔧 Testing Transformation Graph")
    print("=" * 50)
    
    try:
        # Get test data
        sources = await Source.list()
        transformations = await Transformation.list()
        
        if not sources or not transformations:
            print("❌ No sources or transformations available")
            return False
        
        test_source = sources[0]
        test_transformation = transformations[0]
        
        print(f"Testing with source: {test_source.id}")
        print(f"Testing with transformation: {test_transformation.name}")
        
        # Import and run transformation graph
        from open_notebook.graphs.transformation import graph as transform_graph
        
        print("Running transformation graph...")
        result = await transform_graph.ainvoke(
            dict(source=test_source, transformation=test_transformation)
        )
        
        print(f"✅ Transformation completed")
        print(f"Output: {result.get('output', 'No output')[:100]}...")
        
        return True
        
    except Exception as e:
        print(f"❌ Transformation graph test failed: {e}")
        logger.exception(e)
        return False


async def main():
    """Main test function"""
    print("🚀 Starting Insight Generation Tests")
    print("=" * 60)
    
    # Test 1: Direct insight creation
    test1_success = await test_insight_generation()
    
    # Test 2: Transformation graph
    test2_success = await test_transformation_graph()
    
    print("\n📊 Test Results")
    print("=" * 30)
    print(f"Direct insight creation: {'✅ PASS' if test1_success else '❌ FAIL'}")
    print(f"Transformation graph: {'✅ PASS' if test2_success else '❌ FAIL'}")
    
    if test1_success and test2_success:
        print("\n🎉 All tests passed!")
        return 0
    else:
        print("\n💥 Some tests failed!")
        return 1


if __name__ == "__main__":
    exit_code = asyncio.run(main())
    sys.exit(exit_code)
